# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque-lock-timeout-process-aware}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manuel Gomez"]
  s.date = %q{2010-10-20}
  s.description = %q{}
  s.email = %q{manuel@inakanetworks.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "HISTORY.md",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/resque-lock-timeout.rb",
     "lib/resque/plugins/lock_timeout.rb",
     "test/lock_test.rb",
     "test/redis-test.conf",
     "test/test_helper.rb",
     "test/test_jobs.rb"
  ]
  s.homepage = %q{http://github.com/mergoc/resque-lock-timeout-process-aware}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Forf of resque-lock-timeout that checks a saved process id to make sure the process is still running}
  s.test_files = [
    "test/lock_test.rb",
     "test/test_jobs.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

